[package]
name = "mb-proto-mesh"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
bytes = { workspace = true }
mb-endpoint = { path = "../mb-endpoint" }
serde = { workspace = true }
thiserror = { workspace = true }
bincode = { workspace = true }
chacha20poly1305 = { workspace = true }
hkdf = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
