[package]
name = "mesh-bus-observer-metrics"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
mesh-bus-core = { path = "../mesh-bus-core" }
async-trait = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
